# axis_linear:
#   x: 1
#   y: 0
# scale_linear:
#   x: 0.5
#   y: 0.5
# scale_linear_turbo:
#   x: 1.6
#   y: 1.6
# axis_angular:
#   yaw: 3
# scale_angular:
#   yaw: 0.8
# scale_angular_turbo:
#   yaw: 1.2
# enable_button: 4
# enable_turbo_button: 5

# -----------------------------

## Axis mapping

# Control de posicion
axis_position_map:
  x: 1
  y: 0

# Control de orientación
axis_orientation_map:
  z: 3

# Button mapping
enable_mov: 4
increment_velocity: 6
decrement_velocity: 7

# Velocidad maxima
max_displacement_in_a_second: 12.5
